# Generated by Django 4.2.1 on 2023-06-04 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadPrescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='prescription-images/')),
            ],
        ),
        migrations.AlterField(
            model_name='orders',
            name='medicines',
            field=models.ManyToManyField(to='api.ordermedicine'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='order_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled')], default='Pending', max_length=200),
        ),
        migrations.AlterField(
            model_name='orders',
            name='prescription',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
